server:
    port: 8080
spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/education?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
        username: root
        password: root
    jpa:
        show-sql: true # 默认false，在日志里显示执行的sql语句
        database: mysql
        hibernate.ddl-auto: update #指定为update，每次启动项目检测表结构有变化的时候会新增字段，表不存在时会新建，如果指定create，则每次启动项目都会清空数据并删除表，再新建
        properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
        database-platform: org.hibernate.dialect.MySQL5Dialect
        hibernate:
            naming:
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl #指定jpa的自动表生成策略，驼峰自动映射为下划线格式
                #physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    #yml写法，确保resources在Spring下即可
    mvc:
        static-path-pattern: /**
        # 默认值为 classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
    thymeleaf:
        prefix: classpath:/static/
    profiles:
        #区分springboot是线上还是线下环境
        active: '@profileActive@'

logging:
  level:
    org.springframework.web: INFO
    com.github.binarywang.demo.wx.mp: DEBUG
    me.chanjar.weixin: DEBUG
wx:
  mp:
    configs:
      - appId: wxa1258a21fb9d52ad
        secret: 878f133b5069c351762f7a57ff13f073
        token: e10adc3949ba59abbe56e057f20f883e
        aesKey: aKRN9HSmymDFhMY8NwngpjqsOssFpK4dbJQ7I0ukDG1








